// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"time"

	"github.com/KlimKlimKlimKlim/trossage-backend/internal/model"
	"github.com/KlimKlimKlimKlim/trossage-backend/internal/repository"
	mock "github.com/stretchr/testify/mock"
)

// NewRepository creates a new instance of Repository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *Repository {
	mock := &Repository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

type Repository_Expecter struct {
	mock *mock.Mock
}

func (_m *Repository) EXPECT() *Repository_Expecter {
	return &Repository_Expecter{mock: &_m.Mock}
}

// CountChatMessages provides a mock function for the type Repository
func (_mock *Repository) CountChatMessages(ctx context.Context, chatID int64) (int, error) {
	ret := _mock.Called(ctx, chatID)

	if len(ret) == 0 {
		panic("no return value specified for CountChatMessages")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) (int, error)); ok {
		return returnFunc(ctx, chatID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) int); ok {
		r0 = returnFunc(ctx, chatID)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = returnFunc(ctx, chatID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Repository_CountChatMessages_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountChatMessages'
type Repository_CountChatMessages_Call struct {
	*mock.Call
}

// CountChatMessages is a helper method to define mock.On call
//   - ctx context.Context
//   - chatID int64
func (_e *Repository_Expecter) CountChatMessages(ctx interface{}, chatID interface{}) *Repository_CountChatMessages_Call {
	return &Repository_CountChatMessages_Call{Call: _e.mock.On("CountChatMessages", ctx, chatID)}
}

func (_c *Repository_CountChatMessages_Call) Run(run func(ctx context.Context, chatID int64)) *Repository_CountChatMessages_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Repository_CountChatMessages_Call) Return(n int, err error) *Repository_CountChatMessages_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *Repository_CountChatMessages_Call) RunAndReturn(run func(ctx context.Context, chatID int64) (int, error)) *Repository_CountChatMessages_Call {
	_c.Call.Return(run)
	return _c
}

// CountUserChats provides a mock function for the type Repository
func (_mock *Repository) CountUserChats(ctx context.Context, userID int64) (int, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for CountUserChats")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) (int, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) int); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Repository_CountUserChats_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountUserChats'
type Repository_CountUserChats_Call struct {
	*mock.Call
}

// CountUserChats is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
func (_e *Repository_Expecter) CountUserChats(ctx interface{}, userID interface{}) *Repository_CountUserChats_Call {
	return &Repository_CountUserChats_Call{Call: _e.mock.On("CountUserChats", ctx, userID)}
}

func (_c *Repository_CountUserChats_Call) Run(run func(ctx context.Context, userID int64)) *Repository_CountUserChats_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Repository_CountUserChats_Call) Return(n int, err error) *Repository_CountUserChats_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *Repository_CountUserChats_Call) RunAndReturn(run func(ctx context.Context, userID int64) (int, error)) *Repository_CountUserChats_Call {
	_c.Call.Return(run)
	return _c
}

// CountUsersByLoginPrefix provides a mock function for the type Repository
func (_mock *Repository) CountUsersByLoginPrefix(ctx context.Context, userID int64, prefix string) (int, error) {
	ret := _mock.Called(ctx, userID, prefix)

	if len(ret) == 0 {
		panic("no return value specified for CountUsersByLoginPrefix")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, string) (int, error)); ok {
		return returnFunc(ctx, userID, prefix)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, string) int); ok {
		r0 = returnFunc(ctx, userID, prefix)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64, string) error); ok {
		r1 = returnFunc(ctx, userID, prefix)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Repository_CountUsersByLoginPrefix_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountUsersByLoginPrefix'
type Repository_CountUsersByLoginPrefix_Call struct {
	*mock.Call
}

// CountUsersByLoginPrefix is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
//   - prefix string
func (_e *Repository_Expecter) CountUsersByLoginPrefix(ctx interface{}, userID interface{}, prefix interface{}) *Repository_CountUsersByLoginPrefix_Call {
	return &Repository_CountUsersByLoginPrefix_Call{Call: _e.mock.On("CountUsersByLoginPrefix", ctx, userID, prefix)}
}

func (_c *Repository_CountUsersByLoginPrefix_Call) Run(run func(ctx context.Context, userID int64, prefix string)) *Repository_CountUsersByLoginPrefix_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *Repository_CountUsersByLoginPrefix_Call) Return(n int, err error) *Repository_CountUsersByLoginPrefix_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *Repository_CountUsersByLoginPrefix_Call) RunAndReturn(run func(ctx context.Context, userID int64, prefix string) (int, error)) *Repository_CountUsersByLoginPrefix_Call {
	_c.Call.Return(run)
	return _c
}

// CreateMessage provides a mock function for the type Repository
func (_mock *Repository) CreateMessage(ctx context.Context, chatID int64, senderID int64, text string) (model.Message, error) {
	ret := _mock.Called(ctx, chatID, senderID, text)

	if len(ret) == 0 {
		panic("no return value specified for CreateMessage")
	}

	var r0 model.Message
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, int64, string) (model.Message, error)); ok {
		return returnFunc(ctx, chatID, senderID, text)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, int64, string) model.Message); ok {
		r0 = returnFunc(ctx, chatID, senderID, text)
	} else {
		r0 = ret.Get(0).(model.Message)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64, int64, string) error); ok {
		r1 = returnFunc(ctx, chatID, senderID, text)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Repository_CreateMessage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateMessage'
type Repository_CreateMessage_Call struct {
	*mock.Call
}

// CreateMessage is a helper method to define mock.On call
//   - ctx context.Context
//   - chatID int64
//   - senderID int64
//   - text string
func (_e *Repository_Expecter) CreateMessage(ctx interface{}, chatID interface{}, senderID interface{}, text interface{}) *Repository_CreateMessage_Call {
	return &Repository_CreateMessage_Call{Call: _e.mock.On("CreateMessage", ctx, chatID, senderID, text)}
}

func (_c *Repository_CreateMessage_Call) Run(run func(ctx context.Context, chatID int64, senderID int64, text string)) *Repository_CreateMessage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *Repository_CreateMessage_Call) Return(message model.Message, err error) *Repository_CreateMessage_Call {
	_c.Call.Return(message, err)
	return _c
}

func (_c *Repository_CreateMessage_Call) RunAndReturn(run func(ctx context.Context, chatID int64, senderID int64, text string) (model.Message, error)) *Repository_CreateMessage_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteExpiredTokens provides a mock function for the type Repository
func (_mock *Repository) DeleteExpiredTokens(ctx context.Context, olderThan time.Time) (int64, error) {
	ret := _mock.Called(ctx, olderThan)

	if len(ret) == 0 {
		panic("no return value specified for DeleteExpiredTokens")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, time.Time) (int64, error)); ok {
		return returnFunc(ctx, olderThan)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, time.Time) int64); ok {
		r0 = returnFunc(ctx, olderThan)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, time.Time) error); ok {
		r1 = returnFunc(ctx, olderThan)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Repository_DeleteExpiredTokens_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteExpiredTokens'
type Repository_DeleteExpiredTokens_Call struct {
	*mock.Call
}

// DeleteExpiredTokens is a helper method to define mock.On call
//   - ctx context.Context
//   - olderThan time.Time
func (_e *Repository_Expecter) DeleteExpiredTokens(ctx interface{}, olderThan interface{}) *Repository_DeleteExpiredTokens_Call {
	return &Repository_DeleteExpiredTokens_Call{Call: _e.mock.On("DeleteExpiredTokens", ctx, olderThan)}
}

func (_c *Repository_DeleteExpiredTokens_Call) Run(run func(ctx context.Context, olderThan time.Time)) *Repository_DeleteExpiredTokens_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 time.Time
		if args[1] != nil {
			arg1 = args[1].(time.Time)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Repository_DeleteExpiredTokens_Call) Return(n int64, err error) *Repository_DeleteExpiredTokens_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *Repository_DeleteExpiredTokens_Call) RunAndReturn(run func(ctx context.Context, olderThan time.Time) (int64, error)) *Repository_DeleteExpiredTokens_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteRevokedTokens provides a mock function for the type Repository
func (_mock *Repository) DeleteRevokedTokens(ctx context.Context, olderThan time.Time) (int64, error) {
	ret := _mock.Called(ctx, olderThan)

	if len(ret) == 0 {
		panic("no return value specified for DeleteRevokedTokens")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, time.Time) (int64, error)); ok {
		return returnFunc(ctx, olderThan)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, time.Time) int64); ok {
		r0 = returnFunc(ctx, olderThan)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, time.Time) error); ok {
		r1 = returnFunc(ctx, olderThan)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Repository_DeleteRevokedTokens_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteRevokedTokens'
type Repository_DeleteRevokedTokens_Call struct {
	*mock.Call
}

// DeleteRevokedTokens is a helper method to define mock.On call
//   - ctx context.Context
//   - olderThan time.Time
func (_e *Repository_Expecter) DeleteRevokedTokens(ctx interface{}, olderThan interface{}) *Repository_DeleteRevokedTokens_Call {
	return &Repository_DeleteRevokedTokens_Call{Call: _e.mock.On("DeleteRevokedTokens", ctx, olderThan)}
}

func (_c *Repository_DeleteRevokedTokens_Call) Run(run func(ctx context.Context, olderThan time.Time)) *Repository_DeleteRevokedTokens_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 time.Time
		if args[1] != nil {
			arg1 = args[1].(time.Time)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Repository_DeleteRevokedTokens_Call) Return(n int64, err error) *Repository_DeleteRevokedTokens_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *Repository_DeleteRevokedTokens_Call) RunAndReturn(run func(ctx context.Context, olderThan time.Time) (int64, error)) *Repository_DeleteRevokedTokens_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteUser provides a mock function for the type Repository
func (_mock *Repository) DeleteUser(ctx context.Context, userID int64) error {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteUser")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Repository_DeleteUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteUser'
type Repository_DeleteUser_Call struct {
	*mock.Call
}

// DeleteUser is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
func (_e *Repository_Expecter) DeleteUser(ctx interface{}, userID interface{}) *Repository_DeleteUser_Call {
	return &Repository_DeleteUser_Call{Call: _e.mock.On("DeleteUser", ctx, userID)}
}

func (_c *Repository_DeleteUser_Call) Run(run func(ctx context.Context, userID int64)) *Repository_DeleteUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Repository_DeleteUser_Call) Return(err error) *Repository_DeleteUser_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Repository_DeleteUser_Call) RunAndReturn(run func(ctx context.Context, userID int64) error) *Repository_DeleteUser_Call {
	_c.Call.Return(run)
	return _c
}

// InsertChat provides a mock function for the type Repository
func (_mock *Repository) InsertChat(ctx context.Context, chatType model.ChatType) (model.Chat, error) {
	ret := _mock.Called(ctx, chatType)

	if len(ret) == 0 {
		panic("no return value specified for InsertChat")
	}

	var r0 model.Chat
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.ChatType) (model.Chat, error)); ok {
		return returnFunc(ctx, chatType)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.ChatType) model.Chat); ok {
		r0 = returnFunc(ctx, chatType)
	} else {
		r0 = ret.Get(0).(model.Chat)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, model.ChatType) error); ok {
		r1 = returnFunc(ctx, chatType)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Repository_InsertChat_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InsertChat'
type Repository_InsertChat_Call struct {
	*mock.Call
}

// InsertChat is a helper method to define mock.On call
//   - ctx context.Context
//   - chatType model.ChatType
func (_e *Repository_Expecter) InsertChat(ctx interface{}, chatType interface{}) *Repository_InsertChat_Call {
	return &Repository_InsertChat_Call{Call: _e.mock.On("InsertChat", ctx, chatType)}
}

func (_c *Repository_InsertChat_Call) Run(run func(ctx context.Context, chatType model.ChatType)) *Repository_InsertChat_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 model.ChatType
		if args[1] != nil {
			arg1 = args[1].(model.ChatType)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Repository_InsertChat_Call) Return(chat model.Chat, err error) *Repository_InsertChat_Call {
	_c.Call.Return(chat, err)
	return _c
}

func (_c *Repository_InsertChat_Call) RunAndReturn(run func(ctx context.Context, chatType model.ChatType) (model.Chat, error)) *Repository_InsertChat_Call {
	_c.Call.Return(run)
	return _c
}

// InsertChatParticipants provides a mock function for the type Repository
func (_mock *Repository) InsertChatParticipants(ctx context.Context, chatID int64, userIDs ...int64) error {
	var tmpRet mock.Arguments
	if len(userIDs) > 0 {
		tmpRet = _mock.Called(ctx, chatID, userIDs)
	} else {
		tmpRet = _mock.Called(ctx, chatID)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for InsertChatParticipants")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, ...int64) error); ok {
		r0 = returnFunc(ctx, chatID, userIDs...)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Repository_InsertChatParticipants_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InsertChatParticipants'
type Repository_InsertChatParticipants_Call struct {
	*mock.Call
}

// InsertChatParticipants is a helper method to define mock.On call
//   - ctx context.Context
//   - chatID int64
//   - userIDs ...int64
func (_e *Repository_Expecter) InsertChatParticipants(ctx interface{}, chatID interface{}, userIDs ...interface{}) *Repository_InsertChatParticipants_Call {
	return &Repository_InsertChatParticipants_Call{Call: _e.mock.On("InsertChatParticipants",
		append([]interface{}{ctx, chatID}, userIDs...)...)}
}

func (_c *Repository_InsertChatParticipants_Call) Run(run func(ctx context.Context, chatID int64, userIDs ...int64)) *Repository_InsertChatParticipants_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 []int64
		var variadicArgs []int64
		if len(args) > 2 {
			variadicArgs = args[2].([]int64)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *Repository_InsertChatParticipants_Call) Return(err error) *Repository_InsertChatParticipants_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Repository_InsertChatParticipants_Call) RunAndReturn(run func(ctx context.Context, chatID int64, userIDs ...int64) error) *Repository_InsertChatParticipants_Call {
	_c.Call.Return(run)
	return _c
}

// InsertRefreshToken provides a mock function for the type Repository
func (_mock *Repository) InsertRefreshToken(ctx context.Context, token model.Token) (model.Token, error) {
	ret := _mock.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for InsertRefreshToken")
	}

	var r0 model.Token
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.Token) (model.Token, error)); ok {
		return returnFunc(ctx, token)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.Token) model.Token); ok {
		r0 = returnFunc(ctx, token)
	} else {
		r0 = ret.Get(0).(model.Token)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, model.Token) error); ok {
		r1 = returnFunc(ctx, token)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Repository_InsertRefreshToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InsertRefreshToken'
type Repository_InsertRefreshToken_Call struct {
	*mock.Call
}

// InsertRefreshToken is a helper method to define mock.On call
//   - ctx context.Context
//   - token model.Token
func (_e *Repository_Expecter) InsertRefreshToken(ctx interface{}, token interface{}) *Repository_InsertRefreshToken_Call {
	return &Repository_InsertRefreshToken_Call{Call: _e.mock.On("InsertRefreshToken", ctx, token)}
}

func (_c *Repository_InsertRefreshToken_Call) Run(run func(ctx context.Context, token model.Token)) *Repository_InsertRefreshToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 model.Token
		if args[1] != nil {
			arg1 = args[1].(model.Token)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Repository_InsertRefreshToken_Call) Return(token1 model.Token, err error) *Repository_InsertRefreshToken_Call {
	_c.Call.Return(token1, err)
	return _c
}

func (_c *Repository_InsertRefreshToken_Call) RunAndReturn(run func(ctx context.Context, token model.Token) (model.Token, error)) *Repository_InsertRefreshToken_Call {
	_c.Call.Return(run)
	return _c
}

// InsertUser provides a mock function for the type Repository
func (_mock *Repository) InsertUser(ctx context.Context, user model.AuthUser) (model.AuthUser, error) {
	ret := _mock.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for InsertUser")
	}

	var r0 model.AuthUser
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.AuthUser) (model.AuthUser, error)); ok {
		return returnFunc(ctx, user)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.AuthUser) model.AuthUser); ok {
		r0 = returnFunc(ctx, user)
	} else {
		r0 = ret.Get(0).(model.AuthUser)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, model.AuthUser) error); ok {
		r1 = returnFunc(ctx, user)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Repository_InsertUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InsertUser'
type Repository_InsertUser_Call struct {
	*mock.Call
}

// InsertUser is a helper method to define mock.On call
//   - ctx context.Context
//   - user model.AuthUser
func (_e *Repository_Expecter) InsertUser(ctx interface{}, user interface{}) *Repository_InsertUser_Call {
	return &Repository_InsertUser_Call{Call: _e.mock.On("InsertUser", ctx, user)}
}

func (_c *Repository_InsertUser_Call) Run(run func(ctx context.Context, user model.AuthUser)) *Repository_InsertUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 model.AuthUser
		if args[1] != nil {
			arg1 = args[1].(model.AuthUser)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Repository_InsertUser_Call) Return(authUser model.AuthUser, err error) *Repository_InsertUser_Call {
	_c.Call.Return(authUser, err)
	return _c
}

func (_c *Repository_InsertUser_Call) RunAndReturn(run func(ctx context.Context, user model.AuthUser) (model.AuthUser, error)) *Repository_InsertUser_Call {
	_c.Call.Return(run)
	return _c
}

// IsUserMember provides a mock function for the type Repository
func (_mock *Repository) IsUserMember(ctx context.Context, chatID int64, userID int64) (bool, error) {
	ret := _mock.Called(ctx, chatID, userID)

	if len(ret) == 0 {
		panic("no return value specified for IsUserMember")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, int64) (bool, error)); ok {
		return returnFunc(ctx, chatID, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, int64) bool); ok {
		r0 = returnFunc(ctx, chatID, userID)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64, int64) error); ok {
		r1 = returnFunc(ctx, chatID, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Repository_IsUserMember_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsUserMember'
type Repository_IsUserMember_Call struct {
	*mock.Call
}

// IsUserMember is a helper method to define mock.On call
//   - ctx context.Context
//   - chatID int64
//   - userID int64
func (_e *Repository_Expecter) IsUserMember(ctx interface{}, chatID interface{}, userID interface{}) *Repository_IsUserMember_Call {
	return &Repository_IsUserMember_Call{Call: _e.mock.On("IsUserMember", ctx, chatID, userID)}
}

func (_c *Repository_IsUserMember_Call) Run(run func(ctx context.Context, chatID int64, userID int64)) *Repository_IsUserMember_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *Repository_IsUserMember_Call) Return(b bool, err error) *Repository_IsUserMember_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *Repository_IsUserMember_Call) RunAndReturn(run func(ctx context.Context, chatID int64, userID int64) (bool, error)) *Repository_IsUserMember_Call {
	_c.Call.Return(run)
	return _c
}

// RevokeRefreshTokenByID provides a mock function for the type Repository
func (_mock *Repository) RevokeRefreshTokenByID(ctx context.Context, tokenID int64) error {
	ret := _mock.Called(ctx, tokenID)

	if len(ret) == 0 {
		panic("no return value specified for RevokeRefreshTokenByID")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = returnFunc(ctx, tokenID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Repository_RevokeRefreshTokenByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RevokeRefreshTokenByID'
type Repository_RevokeRefreshTokenByID_Call struct {
	*mock.Call
}

// RevokeRefreshTokenByID is a helper method to define mock.On call
//   - ctx context.Context
//   - tokenID int64
func (_e *Repository_Expecter) RevokeRefreshTokenByID(ctx interface{}, tokenID interface{}) *Repository_RevokeRefreshTokenByID_Call {
	return &Repository_RevokeRefreshTokenByID_Call{Call: _e.mock.On("RevokeRefreshTokenByID", ctx, tokenID)}
}

func (_c *Repository_RevokeRefreshTokenByID_Call) Run(run func(ctx context.Context, tokenID int64)) *Repository_RevokeRefreshTokenByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Repository_RevokeRefreshTokenByID_Call) Return(err error) *Repository_RevokeRefreshTokenByID_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Repository_RevokeRefreshTokenByID_Call) RunAndReturn(run func(ctx context.Context, tokenID int64) error) *Repository_RevokeRefreshTokenByID_Call {
	_c.Call.Return(run)
	return _c
}

// RevokeRefreshTokensByUserID provides a mock function for the type Repository
func (_mock *Repository) RevokeRefreshTokensByUserID(ctx context.Context, userID int64) error {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for RevokeRefreshTokensByUserID")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Repository_RevokeRefreshTokensByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RevokeRefreshTokensByUserID'
type Repository_RevokeRefreshTokensByUserID_Call struct {
	*mock.Call
}

// RevokeRefreshTokensByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
func (_e *Repository_Expecter) RevokeRefreshTokensByUserID(ctx interface{}, userID interface{}) *Repository_RevokeRefreshTokensByUserID_Call {
	return &Repository_RevokeRefreshTokensByUserID_Call{Call: _e.mock.On("RevokeRefreshTokensByUserID", ctx, userID)}
}

func (_c *Repository_RevokeRefreshTokensByUserID_Call) Run(run func(ctx context.Context, userID int64)) *Repository_RevokeRefreshTokensByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Repository_RevokeRefreshTokensByUserID_Call) Return(err error) *Repository_RevokeRefreshTokensByUserID_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Repository_RevokeRefreshTokensByUserID_Call) RunAndReturn(run func(ctx context.Context, userID int64) error) *Repository_RevokeRefreshTokensByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// SelectAuthUserByID provides a mock function for the type Repository
func (_mock *Repository) SelectAuthUserByID(ctx context.Context, userID int64) (model.AuthUser, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for SelectAuthUserByID")
	}

	var r0 model.AuthUser
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) (model.AuthUser, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) model.AuthUser); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		r0 = ret.Get(0).(model.AuthUser)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Repository_SelectAuthUserByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SelectAuthUserByID'
type Repository_SelectAuthUserByID_Call struct {
	*mock.Call
}

// SelectAuthUserByID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
func (_e *Repository_Expecter) SelectAuthUserByID(ctx interface{}, userID interface{}) *Repository_SelectAuthUserByID_Call {
	return &Repository_SelectAuthUserByID_Call{Call: _e.mock.On("SelectAuthUserByID", ctx, userID)}
}

func (_c *Repository_SelectAuthUserByID_Call) Run(run func(ctx context.Context, userID int64)) *Repository_SelectAuthUserByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Repository_SelectAuthUserByID_Call) Return(authUser model.AuthUser, err error) *Repository_SelectAuthUserByID_Call {
	_c.Call.Return(authUser, err)
	return _c
}

func (_c *Repository_SelectAuthUserByID_Call) RunAndReturn(run func(ctx context.Context, userID int64) (model.AuthUser, error)) *Repository_SelectAuthUserByID_Call {
	_c.Call.Return(run)
	return _c
}

// SelectAuthUserByLogin provides a mock function for the type Repository
func (_mock *Repository) SelectAuthUserByLogin(ctx context.Context, login string) (model.AuthUser, error) {
	ret := _mock.Called(ctx, login)

	if len(ret) == 0 {
		panic("no return value specified for SelectAuthUserByLogin")
	}

	var r0 model.AuthUser
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (model.AuthUser, error)); ok {
		return returnFunc(ctx, login)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) model.AuthUser); ok {
		r0 = returnFunc(ctx, login)
	} else {
		r0 = ret.Get(0).(model.AuthUser)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, login)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Repository_SelectAuthUserByLogin_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SelectAuthUserByLogin'
type Repository_SelectAuthUserByLogin_Call struct {
	*mock.Call
}

// SelectAuthUserByLogin is a helper method to define mock.On call
//   - ctx context.Context
//   - login string
func (_e *Repository_Expecter) SelectAuthUserByLogin(ctx interface{}, login interface{}) *Repository_SelectAuthUserByLogin_Call {
	return &Repository_SelectAuthUserByLogin_Call{Call: _e.mock.On("SelectAuthUserByLogin", ctx, login)}
}

func (_c *Repository_SelectAuthUserByLogin_Call) Run(run func(ctx context.Context, login string)) *Repository_SelectAuthUserByLogin_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Repository_SelectAuthUserByLogin_Call) Return(authUser model.AuthUser, err error) *Repository_SelectAuthUserByLogin_Call {
	_c.Call.Return(authUser, err)
	return _c
}

func (_c *Repository_SelectAuthUserByLogin_Call) RunAndReturn(run func(ctx context.Context, login string) (model.AuthUser, error)) *Repository_SelectAuthUserByLogin_Call {
	_c.Call.Return(run)
	return _c
}

// SelectChatBetweenUsers provides a mock function for the type Repository
func (_mock *Repository) SelectChatBetweenUsers(ctx context.Context, userID1 int64, userID2 int64) (int64, error) {
	ret := _mock.Called(ctx, userID1, userID2)

	if len(ret) == 0 {
		panic("no return value specified for SelectChatBetweenUsers")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, int64) (int64, error)); ok {
		return returnFunc(ctx, userID1, userID2)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, int64) int64); ok {
		r0 = returnFunc(ctx, userID1, userID2)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64, int64) error); ok {
		r1 = returnFunc(ctx, userID1, userID2)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Repository_SelectChatBetweenUsers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SelectChatBetweenUsers'
type Repository_SelectChatBetweenUsers_Call struct {
	*mock.Call
}

// SelectChatBetweenUsers is a helper method to define mock.On call
//   - ctx context.Context
//   - userID1 int64
//   - userID2 int64
func (_e *Repository_Expecter) SelectChatBetweenUsers(ctx interface{}, userID1 interface{}, userID2 interface{}) *Repository_SelectChatBetweenUsers_Call {
	return &Repository_SelectChatBetweenUsers_Call{Call: _e.mock.On("SelectChatBetweenUsers", ctx, userID1, userID2)}
}

func (_c *Repository_SelectChatBetweenUsers_Call) Run(run func(ctx context.Context, userID1 int64, userID2 int64)) *Repository_SelectChatBetweenUsers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *Repository_SelectChatBetweenUsers_Call) Return(n int64, err error) *Repository_SelectChatBetweenUsers_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *Repository_SelectChatBetweenUsers_Call) RunAndReturn(run func(ctx context.Context, userID1 int64, userID2 int64) (int64, error)) *Repository_SelectChatBetweenUsers_Call {
	_c.Call.Return(run)
	return _c
}

// SelectChatByID provides a mock function for the type Repository
func (_mock *Repository) SelectChatByID(ctx context.Context, chatID int64) (model.Chat, error) {
	ret := _mock.Called(ctx, chatID)

	if len(ret) == 0 {
		panic("no return value specified for SelectChatByID")
	}

	var r0 model.Chat
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) (model.Chat, error)); ok {
		return returnFunc(ctx, chatID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) model.Chat); ok {
		r0 = returnFunc(ctx, chatID)
	} else {
		r0 = ret.Get(0).(model.Chat)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = returnFunc(ctx, chatID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Repository_SelectChatByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SelectChatByID'
type Repository_SelectChatByID_Call struct {
	*mock.Call
}

// SelectChatByID is a helper method to define mock.On call
//   - ctx context.Context
//   - chatID int64
func (_e *Repository_Expecter) SelectChatByID(ctx interface{}, chatID interface{}) *Repository_SelectChatByID_Call {
	return &Repository_SelectChatByID_Call{Call: _e.mock.On("SelectChatByID", ctx, chatID)}
}

func (_c *Repository_SelectChatByID_Call) Run(run func(ctx context.Context, chatID int64)) *Repository_SelectChatByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Repository_SelectChatByID_Call) Return(chat model.Chat, err error) *Repository_SelectChatByID_Call {
	_c.Call.Return(chat, err)
	return _c
}

func (_c *Repository_SelectChatByID_Call) RunAndReturn(run func(ctx context.Context, chatID int64) (model.Chat, error)) *Repository_SelectChatByID_Call {
	_c.Call.Return(run)
	return _c
}

// SelectChatMembers provides a mock function for the type Repository
func (_mock *Repository) SelectChatMembers(ctx context.Context, chatID int64) ([]int64, error) {
	ret := _mock.Called(ctx, chatID)

	if len(ret) == 0 {
		panic("no return value specified for SelectChatMembers")
	}

	var r0 []int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) ([]int64, error)); ok {
		return returnFunc(ctx, chatID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) []int64); ok {
		r0 = returnFunc(ctx, chatID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]int64)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = returnFunc(ctx, chatID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Repository_SelectChatMembers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SelectChatMembers'
type Repository_SelectChatMembers_Call struct {
	*mock.Call
}

// SelectChatMembers is a helper method to define mock.On call
//   - ctx context.Context
//   - chatID int64
func (_e *Repository_Expecter) SelectChatMembers(ctx interface{}, chatID interface{}) *Repository_SelectChatMembers_Call {
	return &Repository_SelectChatMembers_Call{Call: _e.mock.On("SelectChatMembers", ctx, chatID)}
}

func (_c *Repository_SelectChatMembers_Call) Run(run func(ctx context.Context, chatID int64)) *Repository_SelectChatMembers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Repository_SelectChatMembers_Call) Return(int64s []int64, err error) *Repository_SelectChatMembers_Call {
	_c.Call.Return(int64s, err)
	return _c
}

func (_c *Repository_SelectChatMembers_Call) RunAndReturn(run func(ctx context.Context, chatID int64) ([]int64, error)) *Repository_SelectChatMembers_Call {
	_c.Call.Return(run)
	return _c
}

// SelectMessages provides a mock function for the type Repository
func (_mock *Repository) SelectMessages(ctx context.Context, chatID int64, limit int, offset int) ([]model.Message, error) {
	ret := _mock.Called(ctx, chatID, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for SelectMessages")
	}

	var r0 []model.Message
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, int, int) ([]model.Message, error)); ok {
		return returnFunc(ctx, chatID, limit, offset)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, int, int) []model.Message); ok {
		r0 = returnFunc(ctx, chatID, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Message)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64, int, int) error); ok {
		r1 = returnFunc(ctx, chatID, limit, offset)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Repository_SelectMessages_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SelectMessages'
type Repository_SelectMessages_Call struct {
	*mock.Call
}

// SelectMessages is a helper method to define mock.On call
//   - ctx context.Context
//   - chatID int64
//   - limit int
//   - offset int
func (_e *Repository_Expecter) SelectMessages(ctx interface{}, chatID interface{}, limit interface{}, offset interface{}) *Repository_SelectMessages_Call {
	return &Repository_SelectMessages_Call{Call: _e.mock.On("SelectMessages", ctx, chatID, limit, offset)}
}

func (_c *Repository_SelectMessages_Call) Run(run func(ctx context.Context, chatID int64, limit int, offset int)) *Repository_SelectMessages_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *Repository_SelectMessages_Call) Return(messages []model.Message, err error) *Repository_SelectMessages_Call {
	_c.Call.Return(messages, err)
	return _c
}

func (_c *Repository_SelectMessages_Call) RunAndReturn(run func(ctx context.Context, chatID int64, limit int, offset int) ([]model.Message, error)) *Repository_SelectMessages_Call {
	_c.Call.Return(run)
	return _c
}

// SelectRefreshToken provides a mock function for the type Repository
func (_mock *Repository) SelectRefreshToken(ctx context.Context, userID int64, tokenHash string) (model.Token, error) {
	ret := _mock.Called(ctx, userID, tokenHash)

	if len(ret) == 0 {
		panic("no return value specified for SelectRefreshToken")
	}

	var r0 model.Token
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, string) (model.Token, error)); ok {
		return returnFunc(ctx, userID, tokenHash)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, string) model.Token); ok {
		r0 = returnFunc(ctx, userID, tokenHash)
	} else {
		r0 = ret.Get(0).(model.Token)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64, string) error); ok {
		r1 = returnFunc(ctx, userID, tokenHash)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Repository_SelectRefreshToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SelectRefreshToken'
type Repository_SelectRefreshToken_Call struct {
	*mock.Call
}

// SelectRefreshToken is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
//   - tokenHash string
func (_e *Repository_Expecter) SelectRefreshToken(ctx interface{}, userID interface{}, tokenHash interface{}) *Repository_SelectRefreshToken_Call {
	return &Repository_SelectRefreshToken_Call{Call: _e.mock.On("SelectRefreshToken", ctx, userID, tokenHash)}
}

func (_c *Repository_SelectRefreshToken_Call) Run(run func(ctx context.Context, userID int64, tokenHash string)) *Repository_SelectRefreshToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *Repository_SelectRefreshToken_Call) Return(token model.Token, err error) *Repository_SelectRefreshToken_Call {
	_c.Call.Return(token, err)
	return _c
}

func (_c *Repository_SelectRefreshToken_Call) RunAndReturn(run func(ctx context.Context, userID int64, tokenHash string) (model.Token, error)) *Repository_SelectRefreshToken_Call {
	_c.Call.Return(run)
	return _c
}

// SelectUserByID provides a mock function for the type Repository
func (_mock *Repository) SelectUserByID(ctx context.Context, userID int64) (model.User, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for SelectUserByID")
	}

	var r0 model.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) (model.User, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) model.User); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		r0 = ret.Get(0).(model.User)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Repository_SelectUserByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SelectUserByID'
type Repository_SelectUserByID_Call struct {
	*mock.Call
}

// SelectUserByID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
func (_e *Repository_Expecter) SelectUserByID(ctx interface{}, userID interface{}) *Repository_SelectUserByID_Call {
	return &Repository_SelectUserByID_Call{Call: _e.mock.On("SelectUserByID", ctx, userID)}
}

func (_c *Repository_SelectUserByID_Call) Run(run func(ctx context.Context, userID int64)) *Repository_SelectUserByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Repository_SelectUserByID_Call) Return(user model.User, err error) *Repository_SelectUserByID_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *Repository_SelectUserByID_Call) RunAndReturn(run func(ctx context.Context, userID int64) (model.User, error)) *Repository_SelectUserByID_Call {
	_c.Call.Return(run)
	return _c
}

// SelectUserChats provides a mock function for the type Repository
func (_mock *Repository) SelectUserChats(ctx context.Context, userID int64, limit int, offset int) ([]model.ChatWithDetails, error) {
	ret := _mock.Called(ctx, userID, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for SelectUserChats")
	}

	var r0 []model.ChatWithDetails
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, int, int) ([]model.ChatWithDetails, error)); ok {
		return returnFunc(ctx, userID, limit, offset)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, int, int) []model.ChatWithDetails); ok {
		r0 = returnFunc(ctx, userID, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.ChatWithDetails)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64, int, int) error); ok {
		r1 = returnFunc(ctx, userID, limit, offset)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Repository_SelectUserChats_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SelectUserChats'
type Repository_SelectUserChats_Call struct {
	*mock.Call
}

// SelectUserChats is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
//   - limit int
//   - offset int
func (_e *Repository_Expecter) SelectUserChats(ctx interface{}, userID interface{}, limit interface{}, offset interface{}) *Repository_SelectUserChats_Call {
	return &Repository_SelectUserChats_Call{Call: _e.mock.On("SelectUserChats", ctx, userID, limit, offset)}
}

func (_c *Repository_SelectUserChats_Call) Run(run func(ctx context.Context, userID int64, limit int, offset int)) *Repository_SelectUserChats_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *Repository_SelectUserChats_Call) Return(chatWithDetailss []model.ChatWithDetails, err error) *Repository_SelectUserChats_Call {
	_c.Call.Return(chatWithDetailss, err)
	return _c
}

func (_c *Repository_SelectUserChats_Call) RunAndReturn(run func(ctx context.Context, userID int64, limit int, offset int) ([]model.ChatWithDetails, error)) *Repository_SelectUserChats_Call {
	_c.Call.Return(run)
	return _c
}

// SelectUsersByLoginPrefix provides a mock function for the type Repository
func (_mock *Repository) SelectUsersByLoginPrefix(ctx context.Context, userID int64, prefix string, limit int, offset int) ([]model.User, error) {
	ret := _mock.Called(ctx, userID, prefix, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for SelectUsersByLoginPrefix")
	}

	var r0 []model.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, string, int, int) ([]model.User, error)); ok {
		return returnFunc(ctx, userID, prefix, limit, offset)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, string, int, int) []model.User); ok {
		r0 = returnFunc(ctx, userID, prefix, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64, string, int, int) error); ok {
		r1 = returnFunc(ctx, userID, prefix, limit, offset)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Repository_SelectUsersByLoginPrefix_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SelectUsersByLoginPrefix'
type Repository_SelectUsersByLoginPrefix_Call struct {
	*mock.Call
}

// SelectUsersByLoginPrefix is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
//   - prefix string
//   - limit int
//   - offset int
func (_e *Repository_Expecter) SelectUsersByLoginPrefix(ctx interface{}, userID interface{}, prefix interface{}, limit interface{}, offset interface{}) *Repository_SelectUsersByLoginPrefix_Call {
	return &Repository_SelectUsersByLoginPrefix_Call{Call: _e.mock.On("SelectUsersByLoginPrefix", ctx, userID, prefix, limit, offset)}
}

func (_c *Repository_SelectUsersByLoginPrefix_Call) Run(run func(ctx context.Context, userID int64, prefix string, limit int, offset int)) *Repository_SelectUsersByLoginPrefix_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		var arg4 int
		if args[4] != nil {
			arg4 = args[4].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *Repository_SelectUsersByLoginPrefix_Call) Return(users []model.User, err error) *Repository_SelectUsersByLoginPrefix_Call {
	_c.Call.Return(users, err)
	return _c
}

func (_c *Repository_SelectUsersByLoginPrefix_Call) RunAndReturn(run func(ctx context.Context, userID int64, prefix string, limit int, offset int) ([]model.User, error)) *Repository_SelectUsersByLoginPrefix_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateUser provides a mock function for the type Repository
func (_mock *Repository) UpdateUser(ctx context.Context, user model.AuthUser) (model.AuthUser, error) {
	ret := _mock.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for UpdateUser")
	}

	var r0 model.AuthUser
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.AuthUser) (model.AuthUser, error)); ok {
		return returnFunc(ctx, user)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.AuthUser) model.AuthUser); ok {
		r0 = returnFunc(ctx, user)
	} else {
		r0 = ret.Get(0).(model.AuthUser)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, model.AuthUser) error); ok {
		r1 = returnFunc(ctx, user)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Repository_UpdateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateUser'
type Repository_UpdateUser_Call struct {
	*mock.Call
}

// UpdateUser is a helper method to define mock.On call
//   - ctx context.Context
//   - user model.AuthUser
func (_e *Repository_Expecter) UpdateUser(ctx interface{}, user interface{}) *Repository_UpdateUser_Call {
	return &Repository_UpdateUser_Call{Call: _e.mock.On("UpdateUser", ctx, user)}
}

func (_c *Repository_UpdateUser_Call) Run(run func(ctx context.Context, user model.AuthUser)) *Repository_UpdateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 model.AuthUser
		if args[1] != nil {
			arg1 = args[1].(model.AuthUser)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Repository_UpdateUser_Call) Return(authUser model.AuthUser, err error) *Repository_UpdateUser_Call {
	_c.Call.Return(authUser, err)
	return _c
}

func (_c *Repository_UpdateUser_Call) RunAndReturn(run func(ctx context.Context, user model.AuthUser) (model.AuthUser, error)) *Repository_UpdateUser_Call {
	_c.Call.Return(run)
	return _c
}

// WithTx provides a mock function for the type Repository
func (_mock *Repository) WithTx(ctx context.Context, readOnly bool) (repository.Repository, repository.Commiter, error) {
	ret := _mock.Called(ctx, readOnly)

	if len(ret) == 0 {
		panic("no return value specified for WithTx")
	}

	var r0 repository.Repository
	var r1 repository.Commiter
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, bool) (repository.Repository, repository.Commiter, error)); ok {
		return returnFunc(ctx, readOnly)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, bool) repository.Repository); ok {
		r0 = returnFunc(ctx, readOnly)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(repository.Repository)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, bool) repository.Commiter); ok {
		r1 = returnFunc(ctx, readOnly)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(repository.Commiter)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, bool) error); ok {
		r2 = returnFunc(ctx, readOnly)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// Repository_WithTx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WithTx'
type Repository_WithTx_Call struct {
	*mock.Call
}

// WithTx is a helper method to define mock.On call
//   - ctx context.Context
//   - readOnly bool
func (_e *Repository_Expecter) WithTx(ctx interface{}, readOnly interface{}) *Repository_WithTx_Call {
	return &Repository_WithTx_Call{Call: _e.mock.On("WithTx", ctx, readOnly)}
}

func (_c *Repository_WithTx_Call) Run(run func(ctx context.Context, readOnly bool)) *Repository_WithTx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 bool
		if args[1] != nil {
			arg1 = args[1].(bool)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Repository_WithTx_Call) Return(repository1 repository.Repository, commiter repository.Commiter, err error) *Repository_WithTx_Call {
	_c.Call.Return(repository1, commiter, err)
	return _c
}

func (_c *Repository_WithTx_Call) RunAndReturn(run func(ctx context.Context, readOnly bool) (repository.Repository, repository.Commiter, error)) *Repository_WithTx_Call {
	_c.Call.Return(run)
	return _c
}
