# .mockery.yaml
packages:
  github.com/GlaciemArgentum/trossage-backend/internal/repository:
    config:
      dir: "{{.InterfaceDir}}/../mocks"
      pkgname: "mocks"
      filename: "mock_{{.InterfaceName | snakecase}}.go"
      structname: "{{.InterfaceName}}"
    interfaces:
      Repository:
