services:
  app:
    build: .
    container_name: chat-app
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "80:8080"
    networks:
      - chat-net
    depends_on:
      postgres:
        condition: service_healthy
      migrate:
        condition: service_completed_successfully

  postgres:
    image: postgres:16-alpine
    container_name: chat-postgres
    restart: unless-stopped
    env_file:
      - .env
    environment:
      POSTGRES_INITDB_ARGS: "--auth-host=scram-sha-256"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - chat-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  migrate:
    image: migrate/migrate
    container_name: chat-migrate
    env_file:
      - .env
    networks:
      - chat-net
    volumes:
      - ./migrations:/migrations
    depends_on:
      postgres:
        condition: service_healthy
    entrypoint: sh
    command:
        - -c
        - 'migrate -path=/migrations -database="postgresql://$$POSTGRES_USER:$$POSTGRES_PASSWORD@$$POSTGRES_HOST:$$POSTGRES_PORT/$$POSTGRES_DB?sslmode=$$POSTGRES_SSL_MODE" up'
    restart: on-failure

volumes:
  pgdata:

networks:
  chat-net:
    driver: bridge
