SET lock_timeout = '2s';

SET statement_timeout = '10s';

CREATE TABLE users (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_login text NOT NULL CHECK (CHAR_LENGTH(user_login) <= 30),
    password_hash text NOT NULL,
    display_name text NOT NULL CHECK (CHAR_LENGTH(display_name) <= 30),
    deleted_at timestamptz DEFAULT NULL,
    created_at timestamptz NOT NULL DEFAULT NOW(),
    updated_at timestamptz NOT NULL DEFAULT NOW()
);

CREATE UNIQUE INDEX idx_users_login ON users (user_login)
WHERE
    deleted_at IS NULL;

CREATE OR REPLACE FUNCTION update_updated_at_users ()
    RETURNS TRIGGER
    AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$
LANGUAGE plpgsql;

CREATE TRIGGER set_updated_at_users
    BEFORE UPDATE ON users
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_users ();

