SET lock_timeout = '2s';

SET statement_timeout = '10s';

CREATE TABLE refresh_tokens (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    token_hash text NOT NULL UNIQUE CHECK (char_length(token_hash) = 64),
    expires_at timestamptz NOT NULL,
    revoked_at timestamptz DEFAULT NULL,
    created_at timestamptz NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_refresh_tokens_user_token ON refresh_tokens (user_id, token_hash);

CREATE INDEX idx_refresh_tokens_user_active ON refresh_tokens (user_id)
WHERE
    revoked_at IS NULL;

CREATE INDEX idx_refresh_tokens_expired ON refresh_tokens (expires_at)
WHERE
    revoked_at IS NULL;

CREATE INDEX idx_refresh_tokens_revoked ON refresh_tokens (revoked_at)
WHERE
    revoked_at IS NOT NULL;

