SET lock_timeout = '2s';

SET statement_timeout = '10s';

CREATE TYPE chat_type_enum AS ENUM (
    'private'
);

CREATE TABLE chats (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    chat_type chat_type_enum NOT NULL,
    last_message_text text DEFAULT NULL,
    last_message_sender_id bigint DEFAULT NULL REFERENCES users (id) ON DELETE SET NULL,
    last_message_at timestamptz DEFAULT NULL,
    deleted_at timestamptz DEFAULT NULL,
    created_at timestamptz NOT NULL DEFAULT NOW(),
    updated_at timestamptz NOT NULL DEFAULT NOW()
);

CREATE OR REPLACE FUNCTION update_updated_at_chats ()
    RETURNS TRIGGER
    AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$
LANGUAGE plpgsql;

CREATE TRIGGER set_updated_at_chats
    BEFORE UPDATE ON chats
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_chats ();

CREATE INDEX idx_chats_last_message ON chats (last_message_at DESC NULLS LAST)
WHERE
    deleted_at IS NULL;

CREATE TABLE chat_participants (
    chat_id bigint NOT NULL REFERENCES chats (id) ON DELETE CASCADE,
    user_id bigint NOT NULL REFERENCES users (id) ON DELETE RESTRICT,
    joined_at timestamptz NOT NULL DEFAULT NOW(),
    PRIMARY KEY (chat_id, user_id)
);

CREATE INDEX idx_chat_participants_user ON chat_participants (user_id);

CREATE TABLE messages (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    chat_id bigint NOT NULL REFERENCES chats (id) ON DELETE CASCADE,
    sender_id bigint NOT NULL REFERENCES users (id) ON DELETE RESTRICT,
    message_text text NOT NULL,
    created_at timestamptz NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_messages_chat_created ON messages (chat_id, created_at DESC);

CREATE OR REPLACE FUNCTION update_chat_last_message ()
    RETURNS TRIGGER
    AS $$
BEGIN
    UPDATE
        chats
    SET
        last_message_text = NEW.message_text,
        last_message_sender_id = NEW.sender_id,
        last_message_at = NEW.created_at
    WHERE
        id = NEW.chat_id;
    RETURN NEW;
END;
$$
LANGUAGE plpgsql;

CREATE TRIGGER update_chat_on_message
    AFTER INSERT ON messages
    FOR EACH ROW
    EXECUTE FUNCTION update_chat_last_message ();

